# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  unit-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

     #strategy:
       #matrix:
        #node-version: [16.17.0]
       
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
       #- name: use Node.js $({matrix-node-version})
         #uses: action/setup-node@v3
         #with:
           #node-version: $({matrix-node-version})
           #cache: 'npm'

      # Runs a set of commands using the runners shell
      - name: Setup
        run: npm install
      - name: Test
        run: npm run test:unit
          
  build:

    runs-on: ubuntu-latest

     #strategy:
       #matrix:
        #node-version: [16.17.0]
       
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
       #- name: use Node.js $({matrix-node-version})
         #uses: action/setup-node@v3
         #with:
           #node-version: $({matrix-node-version})
           #cache: 'npm'

      # Runs a set of commands using the runners shell
      - name: Setup
        run: npm ci
      - name: Test
        run: npm run build

  docker-build:

    runs-on: ubuntu-latest

     #strategy:
       #matrix:
        #node-version: [16.17.0]
       
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-push-action@v2
        
      -
        name: Build
        uses: docker/build-push-push-action@v2
        with:
          -tags: bad54/docker-vuejs:latest